name: "CI/CD"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix-shell --run "npm install && npm run build"
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v4
    - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.cluster021.hosting.ovh.net
        username: francoo
        password: ${{secrets.FTP_PASSWORD}}
        local-dir: dist/
        server-dir: www/
        dangerous-clean-slate: true
